version: "3.8"
services:

  php-fpm:
    image: php:7.4-fpm-alpine
    networks:
      - proxy-party
    volumes:
      - ./php/welcome.php:/srv/app/public/welcome.php

  nginx:
    image: nginx:alpine
    ports:
      - 8111:80
    networks:
      - proxy-party
    depends_on:
      - php-fpm
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf

  haproxy:
    image: haproxy:2.2-alpine
    ports:
      - 8112:80
    networks:
      - proxy-party
    depends_on:
      - php-fpm
    volumes:
      - ./haproxy/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg

networks:
  proxy-party:
